### ISSUE TITLE
Version 29.1 has been released

### ISSUE THREAD

**Issue by TheSamsai** [flathub/org.gnu.emacs#57] opened 2023-07-30 13:41 UTC
Hopefully we'll see the new version through Flathub soon as well!

**Comment by muep** [comment] 2023-07-30 13:45
PR #56 addresses this, feel free to grab the test build from there and tell if seems free of regressions to you ☺️

**Comment by TheSamsai** [comment] 2023-07-30 13:49
Nice! I grabbed it and will check how it looks.

**Comment by TheSamsai** [comment] 2023-07-30 16:15
After a bit of testing, the only problem I came across is that Eshell doesn't seem to like working over the tramp-container Podman method.  Not entirely sure where that problem is, but it manifests itself as Eshell not being able to execute programs from the container, even though `which <binary>` reports back a path. Regular shell works though, which is interesting.

I'll see if I can dig into it more, but since the way I access Podman from the sandbox is already pretty hacky, it could just be my fault.

**Comment by elken** [comment] 2023-07-31 12:43
Could be https://github.com/flathub/org.gnu.emacs/issues/14 which I've also just hit trying to test this

**Comment by TheSamsai** [comment] 2023-07-31 17:16
Previously I worked around #14 by relaxing the sandbox via Flatseal and by providing a "podman" script in PATH which calls out to Podman via `flatpak-spawn --host`. This worked, and still works as long as I am just opening shell, but Eshell seems to have trouble with it specifically.

**Comment by muep** [comment] 2023-08-06 19:12
#56 was merged and I would expect the build to show up at flathub soon. Closing this now, but please reopen if it turns out that the build does not get through the pipeline for some reason.

**Closed by muep** 2023-08-06 19:12 UTC
